/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
**/

function evenFibSum(){
  let evenFibs = [];
  let lastVal = 0;
  let currVal = 1;
  let nextVal = 0;

  while (nextVal < 4000000){
    nextVal = lastVal + currVal;
    if (nextVal % 2 === 0){
      evenFibs.push(nextVal);
    }
    lastVal = currVal;
    currVal = nextVal;
  }

  let sum = 0;

  evenFibs.forEach(val => {
    sum += val;
  })

  console.log(sum);
}

evenFibSum();